name: "✨ Feature Request"
description: "Suggest a new feature or improvement"
labels: ["feature"]
body:
  - type: input
    id: summary
    attributes:
      label: "Feature Title"
      placeholder: "Example: 'Add user profile page'"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: "Problem to Solve"
      description: "What user problem or business goal does this feature address?"
      placeholder: "Users need a central place to manage their personal data."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "Suggested Solution"
      placeholder: "Allow users to edit profile information from a new settings page…"

  - type: textarea
    id: acceptance
    attributes:
      label: "Acceptance Criteria"
      placeholder: |
        - User can update first/last name
        - Changes persist on refresh
        - Works on desktop and mobile
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      options:
        - "Critical"
        - "High"
        - "Medium"
        - "Low"